title: Portland Protest Map
description: >- 
  Find out if your loved one is in danger by living close to the Portland protest. 
  I created this tool to better educate others who are just seeing the images on the news and not understanding the geography of the situation.
baseurl: ""
url: ""
